### PR TITLE
Don't check token0 in swapper

### PR DESCRIPTION
**Pull request by wjmelements**
#### Changes
Because token0 < token1, you don't need to call into pair to determine which is token0.
Reviewers @boringcrypto

### CODE REVIEW

**Comment by wjmelements** [comment]
```
Downloading compiler 0.6.12
Compiling 50 files with 0.6.12
@boringcrypto/boring-solidity/contracts/ERC20.sol:22:5: DeclarationError: Identifier already declared.
    bytes32 public immutable DOMAIN_SEPARATOR;
    ^---------------------------------------^
contracts/mocks/ERC20Mock.sol:15:5: The previous declaration is here:
    function DOMAIN_SEPARATOR() public view returns (bytes32) {
    ^ (Relevant source part starts here and spans across multiple lines).

contracts/mocks/ERC20Mock.sol:16:16: DeclarationError: Undeclared identifier.
        return _domainSeparator();
               ^--------------^

Error in plugin solidity-coverage: HardhatError: HH600: Compilation failed
```

Build error is unrelated

**Comment by boringcrypto** [comment]
Ooh, I love this! Very nice find :D

Why the cast to uint160? https://github.com/sushiswap/sushiswap/blob/master/contracts/uniswapv2/UniswapV2Factory.sol#L32

**Comment by wjmelements** [comment]
> Why the cast to uint160? https://github.com/sushiswap/sushiswap/blob/master/contracts/uniswapv2/UniswapV2Factory.sol#L32

I thought it was required for the comparison. Glad it is not.

**Comment by boringcrypto** [comment]
Great, can you do it for both functions: swap and swapExact?

**Comment by wjmelements** [comment]
> Great, can you do it for both functions: swap and swapExact?

Isn't swapExact unused?

**Comment by wjmelements** [comment]
Another thing you can do is use the create2 deterministic address instead of looking it up in the factory

**Review by boringcrypto — APPROVED** [review]

**Comment by boringcrypto** [comment]
Ooh, good point... interestingly, the UniSwap contracts don't use this: https://github.com/sushiswap/sushiswap/blob/master/contracts/uniswapv2/UniswapV2Factory.sol#L13 - do you have the code for it lying around somewhere?

**Pull request merged**
